### PR TITLE
Task 017 and 018: Collectible Orbs

### PR DESCRIPTION
**Pull request by DSF256**
Added 4 orbs to the first level, in addition to a label telling the player how many they've collected (similar to coins).  For now, just ignore the fact that the orbs have the same texture as the coins.

### CODE REVIEW

**Comment by reid-wynkoop** [comment]
Looks like you deleted the title screen... Your branch must not have been up to date when you made the commit. Can you add it back in?

**Review by WilltheWys — APPROVED** [review]
Looks good. Just give the orbs a different sprite so that we can differentiate them from the coins

**Comment by reid-wynkoop** [comment]
Looks good. Side question, does collecting orbs do anything at this time? Or will that be in future commits?

**Review by reid-wynkoop — APPROVED** [review]

**Comment by DSF256** [comment]
The only way to advance to the next level is to collect all 4 orbs.  I'll be putting out another pull request shortly that will be meant to test just that.

**Review by mbagwell — COMMENTED** [review]
I recommend replacing the orb texture with the bullet texture. it is transparent around the corners and doesnt have any whitespace.

**Pull request merged**
