### PR TITLE
Task10: Reset player and rest of level when players health reaches 0.

### PR DESCRIPTION
**Pull request by reid-wynkoop**

### CODE REVIEW

**Review by WilltheWys — COMMENTED** [review]
Every thing here looks good. No issues and a much needed change to the code. Good job.

**Review by DSF256 — CHANGES_REQUESTED** [review]
So, a few things...

First, when jumping on both the furthest left platform and the topmost platform (basically the entire left side of the level), the coin counter mysteriously increases despite the fact that no coins are being collected.  Obviously, this also affects the 1-UP's you can get by collecting 20 coins.  I remember that this had to do with the emit_signal("coinCollected") function being erroneously called (based on our Discord chat).  Also, my game kept playing even after my lives hit and 0 even negative numbers (I got all the way to -19 before I got bored and quit).  Since I see that you're working on a game over screen for when the life counter hits 0 or lower, this is an issue that will probably be fixed.

**Comment by reid-wynkoop** [comment]
@DSF256 Thanks for the feedback, infinite coin bug is fixed in commit 3ad6c52

**Review by mbagwell — COMMENTED** [review]
The settings for the "dead" menu look good.

**Pull request merged**
