### PR TITLE
updated and cleaned up all .gd files we worked on.

### PR DESCRIPTION
**Pull request by reid-wynkoop**
Updated a lot of our code. Made it more readable. Doxygen output will be better by declaring type on vars/methods

### CODE REVIEW

**Review by DSF256 — APPROVED** [review]
Very good work.  I will say that this makes reading through these files much more manageable and intuitive, even without all of the stuff GDScript or our documentation software will do.  I mean, just take a look at some of the var names.  "TextureButton2"?  Very confusing to follow.  "ExitBtn" is much more intuitive to follow.

**Comment by D-B-Cooper** [comment]
Looks pretty good, but you may have a conflict with one a the files. Please fix before pulling.

**Comment by DSF256** [comment]
Yeah, I noticed that conflict after I had already made my review.  It doesn't look that bad, though; for Coin.gd it just looks like GitHub is being stupid.  I remember having a rough time with trying to resolve a conflict in one of my own pull requests.

**Review by mbagwell — APPROVED** [review]
Nice job editing the .gd files(like in player.gd). However, there are a couple of conflicting files.

**Pull request merged**
